title: ShaominXie's Homepage
# page-top-title: Master's student
site_description: Master's student

email: "xieshaomin0805@163.com"
top-section-bg-text: Be what you wanna be
home-subtitle: Shaomin Xie&ensp;|&ensp;谢少敏
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
